COURSE_ACTS(COURSE_BOB, _(" 1 CAMPAGNA DI BOB-OMBA"),
       _("BOSS BOB-OMBA SULLA CIMA")     , _("GARA CON KOOPA IL VELOCE") , _("LANCIO SULL'ISOLA NEL CIELO"),
       _("TROVA LE 8 MONETE ROSSE")          , _("MARIO SPICCA IL VOLO")        , _("DIETRO IL CANCELLO DI CATEGNACCIO"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTEZZA DI RE WOMP"),
       _("UN RE WOMP ARRABBIATO")        , _("IN CIMA ALLA FORTEZZA")    , _("LANCIO NEL BLU DIPINTO DI BLU"),
       _("MONETE ROSSE SULLE ISOLE SOSPESE"), _("CADUTA SULL'ISOLA INGABBIATA")    , _("BRECCIA NEL MURO"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAIA PIRATA"),
       _("BOTTINO DELLA NAVE AFFONDATA")    , _("VIENI FUORI, GRANDE MURENA") , _("TESORO NELLA GROTTA SUBACQUEA"),
       _("MONETE ROSSE SULLA NAVE GALLEGGIANTE")  , _("AFFERRA IL PILASTRO IN PIETRA")     , _("ATTRAVERSO IL GETTO D'ACQUA"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTE REFRIGERIO"),
       _("SUPER SCIVOLO NEVOSO")             , _("SMARRITA PICCOLA PINGUINA...")             , _("SFIDA AL PINGUINO GIGANTE"),
       _("SCIVOLATA GELIDA PER 8 MONETE ROSSE")  , _("IL PUPAZZO ROTOLANTE")       , _("SUPER SALTO A PARETE DI MARIO"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANIERO DEI BOO"),
       _("A CACCIA DI FANTASMI")            , _("GIOSTRA FANTASMAGORICA") , _("MISTERO DEI LIBRI INFESTATI"),
       _("ALLA RICERCA DI MONETE ROSSE")          , _("BALCONE DEL RE")             , _("OCCHI APERTI NELLA STANZA SEGRETA!"))

COURSE_ACTS(COURSE_HMC, _(" 6 CAVERNA NEBBIOSA"),
       _("IL MOSTRO DEL LAGO")  , _("L'ASCENSIONE COSTA 8 MONETE ROSSE")       , _("SCATTO DI METALLO"),
       _("FUGA DAL LABIRINTO TOSSICO")     , _("IL LABIRINTO HA UN'USCITA SEGRETA")     , _("SEGRETO DEI MASSI IN ROTOLAMENTO"))

COURSE_ACTS(COURSE_LLL, _(" 7 LAGO MAGMATICO"),
       _("FALLO CUOCERE NEL SUO BRODO!")            , _("PRENDILI PER LE CORNA")             , _("PUZZLE A 15 PEZZI PER 8 MONETE"),
       _("CORSA SUL TRONCO ARDENTE")           , _("IN BOCCA AL VULCANO")  , _("VISITA GUIDATA VULCANICA"))

COURSE_ACTS(COURSE_SSL, _(" 8 DESERTO BOLLENTE"),
       _("TRA GLI ARTIGLI DEL RAPACE") , _("PUNTA SCINTILLANTE DELLA PIRAMIDE")      , _("ESPLORAZIONE DELLA PIRAMIDE ANTICA"),
       _("SIGILLO DEI QUATTRO PILASTRI"), _("MONETE ROSSE IN VOLO LIBERO")   , _("ENIGMA DELLA PIRAMIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 BANCHINE TENEBROSE"),
       _("SOTTOMARINO DI BOWSER")            , _("SCRIGNI PORTATI DALLA CORRENTE")         , _("MONETE ROSSE DEL FUGGITIVO BOWSER"),
       _("CONTROCORRENTE")        , _("LA RICOMPENSA DELLA MANTA")        , _("COLLEZIONE DEI CAPPELLI"))

COURSE_ACTS(COURSE_SL, _("10 TERRA INNEVATA"),
       _("QUEL TESTONE DI UN PUPAZZO")            , _("DUELLO DEL GELO")          , _("NEL PROFONDO GELO"),
       _("VOLA OLTRE IL LAGO GELATO")  , _("8 MONETE SFRECCIANDO SUL GUSCIO") , _("MARIO NELL'IGLÙ"))

COURSE_ACTS(COURSE_WDW, _("11 CITTÀ BAGNASCIUGA"),
       _("INDICAZIONI SCIOCCANTI!")         , _("DALL'ALTO DELLA CITTÀ")               , _("SEGRETI NELLE SECCHE E IN CIELO"),
       _("ASCENSORE ESPRESSO - AFFRETTARSI!")   , _("MONETE ROSSE IN CITTÀ")      , _("GARA IN CENTRO!"))

COURSE_ACTS(COURSE_TTM, _("12 VETTA PROMINENTE"),
       _("UNA MONTAGNA DA SCALARE")            , _("MISTERO DELLA GABBIA DI UKIKI")    , _("MONETE ROSSE SUI FUNGHI GIGANTI"),
       _("PENDIO MONTANO MISTERIOSO")       , _("PANORAMA MOZZAFIATO DAL PONTE") , _("LANCIO SUL FUNGO SOLITARIO"))

COURSE_ACTS(COURSE_THI, _("13 ISOLA GRANPICCOLA"),
       _("ESTIRPAZIONE PIANTE PIRANHA")      , _("IL CUCUZZOLO DELL'ISOLA"), _("RIVINCITA CON KOOPA IL VELOCE"),
       _("CINQUE SEGRETI MINUSCOLI")       , _("MONETE ROSSE DEL TORCIBRUCO")           , _("FILO DA TORCERE PER TORCIBRUCO"))

COURSE_ACTS(COURSE_TTC, _("14 PENDOLO TICCHETTANTE"),
       _("DRITTO IN GABBIA")            , _("STANZA DEI PENDOLI")     , _("LA LANCETTA DEL RINTOCCO"),
       _("CORONA DEL TWOMP")           , _("SALTI SINCRONIZZATI")    , _("ORA ZERO DELLE MONETE ROSSE"))

COURSE_ACTS(COURSE_RR, _("15 CORSO ARCOBALENO"),
       _("IN CROCIERA SULL'ARCOBALENO")  , _("GRANDE CASA NEL CIELO")      , _("MONETE ROSSE NEL LABIRINTO"),
       _("DONDOLANDO NELLA BREZZA")        , _("PIRAMIDI INGANNEVOLI!")             , _("ISOLA OLTRE L'ARCOBALENO"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER NEL MONDO OSCURO"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER NEL MARE ARDENTE"))
SECRET_STAR(COURSE_BITS, _("   BOWSER NEL CREPUSCOLO"))
SECRET_STAR(COURSE_PSS, _("   SCIVOLO SEGRETO REGALE"))
SECRET_STAR(COURSE_COTMC, _("   GROTTA METALLICA"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE ARCOBALENO"))
SECRET_STAR(COURSE_VCUTM, _("   FOSSATO SENZA FONDO"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO FRA LE NUVOLE"))
SECRET_STAR(COURSE_SA, _("   ACQUARIO NASCOSTO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("STELLE SEGRETE CASTELLO"))

EXTRA_TEXT(0, _("UNA DELLE STELLE SEGRETE NEL CASTELLO!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
