COURSE_ACTS(COURSE_BOB, _("  1 CAMPAGNA DI BOB-OMBA"),
       _("IL RE DELLA MONTAGNA")     , _("GARA CON KOOPA IL VELOCE") , _("ISOLA SOSPESA NEL MIRINO"),
       _("A CACCIA DELLE 8 MONETE ROSSE")          , _("MARIO SPICCA IL VOLO")        , _("DIETRO IL CANCELLO DI CATEGNACCIO"))

COURSE_ACTS(COURSE_WF, _("  2 FORTEZZA DI RE WOMP"),
       _("UN RE DA DEPORRE")        , _("SUL TETTO DELLA FORTEZZA")    , _("LANCIO NEL BLU DIPINTO DI BLU"),
       _("MONETE ROSSE SULLE ISOLE SOSPESE"), _("CADUTA SULL'ISOLA INGABBIATA")    , _("LA BRECCIA DI PORTA PIA"))

COURSE_ACTS(COURSE_JRB, _("  3 BAIA PIRATA"),
       _("IL BOTTINO DEL GALEONE AFFONDATO")    , _("VIENI FUORI, MURENA GIGANTE!") , _("TESORO NELLA GROTTA SUBACQUEA"),
       _("LE MONETE ROSSE DEL GALEONE A GALLA")  , _("MIRA AL PILASTRO IN PIETRA")     , _("ATTRAVERSO IL GETTO D'ACQUA"))

COURSE_ACTS(COURSE_CCM, _("  4 MONTE REFRIGERIO"),
       _("SUPER SCIVOLO NEVOSO")             , _("AAA - SMARRITA PICCOLA PINGUINA")             , _("GARA COL CAMPIONE DI SLITTINO"),
       _("SCIVOLATA GELIDA PER 8 MONETE ROSSE")  , _("IL PUPAZZO GIOCA A BOCCE")       , _("CHE SUPER SALTO A PARETE!"))

COURSE_ACTS(COURSE_BBH, _("  5 MANIERO DEI BOO"),
       _("ACCHIAPPAFANTASMI")            , _("GIOSTRA FANTASMAGORICA") , _("IL MISTERO DEI LIBRI INFESTATI"),
       _("8 MONETE ROSSE SPETTRALI")          , _("LA TERRAZZA DEL RE FANTASMA")             , _("OCCHI APERTI NELLA STANZA SEGRETA!"))

COURSE_ACTS(COURSE_HMC, _("  6 CAVERNA NEBBIOSA"),
       _("AVVISTATO MOSTRO NEL LAGO!")  , _("L'ASCENSIONE COSTA 8 MONETE ROSSE")       , _("PULSANTE DI SCATTO METALLICO"),
       _("FUGA DAL LABIRINTO TOSSICO")     , _("IL LABIRINTO HA UN'USCITA SEGRETA")     , _("OCCHIO AI MASSI ROTOLANTI"))

COURSE_ACTS(COURSE_LLL, _("  7 LAGUNA MAGMATICA"),
       _("FALLO CUOCERE NEL SUO BRODO!")            , _("PRENDILI PER LE CORNA")             , _("PUZZLE A 15 PEZZI PER 8 MONETE"),
       _("LA CORSA SUL TRONCO ARDENTE")           , _("IN BOCCA AL VULCANO")  , _("UNA VISITA GUIDATA COI FUOCHI"))

COURSE_ACTS(COURSE_SSL, _("  8 DESERTO ABBAGLIANTE"),
       _("NELLE GRINFIE DEL RAPACE") , _("QUELLO STRANO BAGLIORE SULLA PIRAMIDE")      , _("ESPLORAZIONE DELLA PIRAMIDE ANTICA"),
       _("IL SIGILLO DEI QUATTRO PILASTRI"), _("LE MONETE ROSSE NON SONO UN MIRAGGIO")   , _("L'ENIGMA DELLA PIRAMIDE ANTICA"))

COURSE_ACTS(COURSE_DDD, _("  9 ARSENALE TENEBROSO"),
       _("IL SOTTOMARINO DI BOWSER")            , _("SCRIGNI PORTATI DALLA CORRENTE")         , _("LE MONETE ROSSE DEL LATITANTE BOWSER"),
       _("CONTROCORRENTE")        , _("UNA TAGLIA SULLA MANTA")        , _("LA COLLEZIONE DEI CAPPELLI"))

COURSE_ACTS(COURSE_SL, _(" 10 FIORDO INNEVATO"),
       _("QUEL TESTONE DI UN PUPAZZO")            , _("IL DUELLO DEL GELO")          , _("SURGELATO NELLA GHIACCIAIA"),
       _("PATTINA OLTRE IL LAGO GELATO")  , _("MONETE ROSSE SGUSCIANTI") , _("UN IGLÙ BELLO ACCOGLIENTE"))

COURSE_ACTS(COURSE_WDW, _(" 11 CITTÀ BAGNASCIUGA"),
       _("PEDANE ELETTRIZZANTI!")         , _("DALL'ALTO DELLA CITTÀ")               , _("SEGRETI NELLE SECCHE E IN CITTÀ"),
       _("ASCENSORE ESPRESSO - AFFRETTARSI!")   , _("MONETE ROSSE SUL FONDO")      , _("CORSA CONTRO IL TEMPO IN CENTRO"))

COURSE_ACTS(COURSE_TTM, _(" 12 VETTA PROMINENTE"),
       _("UNA MONTAGNA DA SCALARE")            , _("MISTERO DELLA GABBIA DI UKIKI")    , _("MONETE ROSSE E FUNGHI GIGANTI"),
       _("PENDIO MONTANO MISTERIOSO")       , _("PANORAMA MOZZAFIATO DAL PONTE") , _("LANCIO SUL FUNGO SOLITARIO"))

COURSE_ACTS(COURSE_THI, _(" 13 ISOLA GRANPICCOLA"),
       _("ESTIRPAZIONE PIANTE PIRANHA")      , _("IL CUCUZZOLO DELL'ISOLA"), _("LA VENDETTA DI KOOPA IL VELOCE"),
       _("PICCOLI SEGRETI CRESCONO")       , _("LE MONETE ROSSE DEL TORCIBRUCO")           , _("FILO DA TORCERE PER TORCIBRUCO"))

COURSE_ACTS(COURSE_TTC, _(" 14 PENDOLO TICCHETTANTE"),
       _("TEMPO SCADUTO, IN GABBIA!")            , _("IL POZZO E I PENDOLI")     , _("IL RINTOCCO DELLA LANCETTA"),
       _("LA CORONA DEL TWOMP")           , _("SALTI SINCRONIZZATI")    , _("ORA ZERO DELLE MONETE ROSSE"))

COURSE_ACTS(COURSE_RR, _(" 15 PARADISO ARCOBALENO"),
       _("UN BIGLIETTO PER LA CROCIERA")  , _("UNA GRANDE CASA NEL CIELO")      , _("MONETE ROSSE NEL LABIRINTO"),
       _("DONDOLANDO NELLA BREZZA")        , _("OCCHIO AI TRIANGOLI INFIDI!")             , _("L'ISOLA OLTRE L'ARCOBALENO"))

SECRET_STAR(COURSE_BITDW, _("   SI ALLUNGA L'OMBRA DI BOWSER"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER, IL PAVIMENTO È DI LAVA!"))
SECRET_STAR(COURSE_BITS, _("   BOWSER SUL VIALE DEL TRAMONTO"))
SECRET_STAR(COURSE_PSS, _("   LO SCIVOLO DELLA PRINCIPESSA"))
SECRET_STAR(COURSE_COTMC, _("   GROTTA METALLICA"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE IRIDESCENTE"))
SECRET_STAR(COURSE_VCUTM, _("   FOSSATO SENZA FONDO"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO FRA LE NUVOLE"))
SECRET_STAR(COURSE_SA, _("   ACQUARIO NASCOSTO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("  STELLE SEGRETE CASTELLO"))

EXTRA_TEXT(0, _("UNA STELLA SEGRETA DEL CASTELLO!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
